//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplyNowDocumentDbModelManager.Models
{
    using Microsoft.Azure.Documents;
    using System;
    using System.Collections.Generic;
    
    public class ComplianceResponseSet : Resource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComplianceResponseSet()
        {
            this.ComplianceResponses = new HashSet<ComplianceResponse>();
        }

        public System.DateTime StartDateTime { get; set; }

        public int PatientId { get; set; }
    
        public virtual Device Device { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplianceResponse> ComplianceResponses { get; set; }
    }
}
