//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplyNowDocumentDbModelManager.Models
{
    using System;

    public partial class ComplianceEntryDto
    {
        public int EntryNumber { get; set; }

        public bool AllDataAvailable { get; set; }

        public int SubScheduleNumber { get; set; }

        public Nullable<bool> Response { get; set; }

        public int Snoozes { get; set; }

        public int MinutesToRespond { get; set; }

        public int ComplianceResponseId { get; set; }

        public virtual ComplianceResponseDto ComplianceResponse { get; set; }
    }
}
